name: First-Time Deploy Frontend via SSM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Prepare deployment package
        run: |
          mkdir -p deploy-package
          shopt -s dotglob extglob
          cp -r !(deploy-package|.git|node_modules) deploy-package/
          cd deploy-package
          zip -r ../employee-frontend-deploy.zip

      - name: ☁️ Upload to S3
        run: |
          aws s3 cp employee-frontend-deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deployment/employee-frontend/employee-frontend-deploy.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: 🚀 SSM Deploy Script (Frontend Setup)
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ secrets.AWS_REGION }}

          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --region ${{ secrets.AWS_REGION }} \
            --comment "Frontend App Deployment via SSM" \
            --parameters commands='[
              "sudo apt update && sudo apt upgrade -y",
              "sudo apt install -y unzip curl",
              "curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip",
              "unzip -o awscliv2.zip",
              "sudo ./aws/install",
              "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -",
              "sudo apt install -y nodejs build-essential nginx",
              "sudo npm install -g pm2",
              "sudo mkdir -p /var/www/employee-frontend",
              "sudo chown -R $USER:$USER /var/www/employee-frontend",
              "aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/deployment/employee-frontend/employee-frontend-deploy.zip /tmp/employee-frontend-deploy.zip",
              "unzip -o /tmp/employee-frontend-deploy.zip -d /tmp/employee-frontend",
              "cp -r /tmp/employee-frontend/deploy-package/. /var/www/employee-frontend/",
              "cd /var/www/employee-frontend",
              "npm install",
              "npm run build",
              "pm2 start ecosystem.config.cjs",
              "pm2 save",
              "pm2 startup",
              "sudo cp nginx.conf /etc/nginx/sites-available/employee-frontend",
              "sudo ln -s /etc/nginx/sites-available/employee-frontend /etc/nginx/sites-enabled/",
              "sudo rm -f /etc/nginx/sites-enabled/default",
              "sudo nginx -t",
              "sudo systemctl restart nginx"
            ]' \
            --timeout-seconds 1200 \
            --max-concurrency "1" \
            --max-errors "1" \
            --cloud-watch-output-config '{"CloudWatchOutputEnabled":true}'
